workflows:
  royal-flix-apk-build:
    name: "Royal Flix APK Build"
    instance_type: mac_mini_m1
    max_build_duration: 60
    environment:
      android_sdk:
        platforms:
          - 34
        build_tools:
          - 34.0.0
      java: 17
    cache:
      cache_paths:
        - ~/.gradle/caches
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: '*'
          include: true
          source: true
    scripts:
      - name: Make Gradle wrapper executable
        script: chmod +x gradlew
      - name: Build Debug APK
        script: ./gradlew assembleDebug --stacktrace
    artifacts:
      - app/build/outputs/apk/**/*.apk
